.\"	$Id$
.Dd December 25, 2004
.Dt WATCH 1
.Os
.Sh NAME
.Nm watch
.Nd execute program periodically, showing output fullscreen
.Sh SYNOPSIS
.Nm watch
.Op Fl tv
.Op Fl s Ar time
.Op Ar command
.Sh DESCRIPTION
.Nm
runs
.Ar command
repeatedly and displays its output fullscreen.
This allow you to watch an output of the
.Ar command
as it changes.
The default delay between screen updates is 2 seconds.
.Pp
The
.Nm
will terminate with keyboard interrupt 
.Pq Sq ^C
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl s Ar time
Set delay between screen updates in seconds.
.It Fl t
Disable output of title bar.
.It Fl v
Display version and exit.
.El
.Pp
.Sh EXAMPLE
.Nm
-s 1 ps
.Pp
.Sh AUTHORS
The original
.Nm
was written by Tony Rems <rembo@unisoft.com> in 1991,
with mods and corrections by Francois Pinard.
.Pp
It was rewritten by Dimitri Sokolyuk <demon@vhost.dyndns.org> in 2003.
