.\"	$Id$
.Dd December 25, 2004
.Dt WATCH 1
.Os
.Sh NAME
.Nm watch
.Nd execute program periodically, showing output fullscreen
.Sh SYNOPSIS
.Nm watch
.Op Fl nv
.Op Fl s Ar time
.Op Ar command
.Sh DESCRIPTION
The
.Nm
utility runs a
.Ar command
repeatedly and displays its output fullscreen.
This allow you to watch an output of the
.Ar command
as it changes.
If the
.Ar command
is absent,
.Nm
will prompt for it.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl s Ar time
Set delay between screen updates in seconds.
The default delay is 2 seconds.
.It Fl n
Disable output of the title bar.
.It Fl v
Display version and terminate.
.El
.Pp
.Nm Watch
will terminate with the keyboard interrupt
.Pq Sq ^C
.Pp
.Sh EXAMPLE
.Nm
-s 1 ps
.Pp
.Sh HISTORY
The original
.Nm
was written by Tony Rems <rembo@unisoft.com> in 1991,
with mods and corrections by Francois Pinard.
It was rewritten completly from scratch by Dimitri Sokolyuk
<demon@vhost.dyndns.org> in 2003.
