.\"	$Id$
.Dd Juni 05, 2003
.Dt WATCH 1
.Os
.Sh NAME
.Nm watch
.Nd execute program periodically, showing output fullscreen
.Sh SYNOPSIS
.Nm watch
.Op Fl vns Ar <seconds>
.Op Ar command
.Sh DESCRIPTION
.Nm
runs
.Ar command
repeatedly, displaying its output fullscreen.
This allow you to watch a
.Ar command
output as it changes.
By default it updates output every 2 seconds.
.Pp
The
.Nm
will end with keyboard interrupt 
.Pq Sq ^C
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl v
Show version and exit.
.It Fl n
Show no title.
.It Fl s Ar <seconds>
Delay in seconds between screen refresh.
.El
.Pp
.Sh EXAMPLE
.Nm
-s 1 ps x
.Pp
.Sh AUTHORS
The original
.Nm
was written by Tony Rems <rembo@unisoft.com> in 1991,
with mods and corrections by Francois Pinard.
It was rewritten by demon <demon@vhost.dyndns.org> in 2003.
